baseURL = "https://carlgaspar.com/"
title = "Carl Gaspar"
pluralizelisttitles = false

[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4

[params]
  favicon = "/logo.png"
  description = "Security. Code. Homelabs. Basketball. Photography. Life. â€” Personal blog by Carl Gaspar."
  author = "Carl Gaspar"
  [params.theme_config]
    back_home_text = ".."
    date_format = "2006-01-02"
    appearance = "light"
  [params.giscus]
    repo = "carlignn/carlgaspar-nostyleplease"
    repoID = "R_kgDOIDaPAw"
    category = "Comments"
    categoryID = "DIC_kwDOIDaPA84Cz6IE"